spring.application.name=insurance-claim-management-system
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/icms_db
spring.datasource.username=root
spring.datasource.password=6113

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
